### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by pkdc** [anthony-dsouza/social-network#8]
- [x] A user's able to create a group, that have a title and a description given by the creator
- [x] the owner can invite other users to join the group
- [x] invited users need to accept the invitation to be part of the group
- [x] Joined users can invite other people
- [x] A user can also request to enter the group , the creator of the group would be allowed to accept or refuse the request.
- [x] Have a section where you can browse through all groups, and can make a request to enter the selected group
- [x] In a group, a joined user can create posts and comments, these will only be displayed to members of the group.
- [x] #10
- [x] #22
- [x] #83

**Comment by maddiewesst** [comment]
Done
